import{a as k,i as d,S as U,e as x,d as _}from"./assets/vendor-2Hd5OlEu.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))o(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(s){if(s.ep)return;s.ep=!0;const r=n(s);fetch(s.href,r)}})();async function z(){try{const n="https://sound-wave.b.goit.study/api"+"/genres";return(await k.get(n)).data}catch(e){return d.error({message:`${e}`,position:"topRight"}),null}}async function V({currentPage:e=1,name:t="",sortName:n="",genre:o=""}={}){try{const i="https://sound-wave.b.goit.study/api"+"/artists",l={limit:8,page:e,...t&&{name:t},...n&&{sortName:n},...o&&{genre:o}};return(await k.get(i,{params:l})).data}catch(s){return d.error({message:`${s}`,position:"topRight"}),null}}async function D(){try{const n="https://sound-wave.b.goit.study/api"+"/feedbacks",o={limit:12};return(await k.get(n,{params:o})).data}catch(e){return d.error({message:`${e}`,position:"topRight"}),null}}const f="/project-okak/icons.svg";function J(e){const t=e.map(({_id:s,name:r,rating:i,descr:l})=>{const p=Math.round(i*2)/2,v=Array.from({length:5}).map((M,G)=>{const I=Math.min(Math.max(p-G,0),1)*100;return`
      <span class="star-container" style="position: relative; width: 20px; height: 20px; display: inline-block;">
        <svg class="star star--empty" width="20" height="20" style="position: absolute; top: 0; left: 0;">
          <use href="${f}#star" fill="#fff"></use>
        </svg>
        <div class="star-fill-wrapper" style="width: ${I}%; height: 20px; overflow: hidden; position: absolute; top: 0; left: 0;">
          <svg class="star star--filled" width="20" height="20">
            <use href="${f}#star" fill="#764191"></use>
          </svg>
        </div>
      </span>`}).join("");return`
      <div class="swiper-slide" data-id="${s}">
        <div class="star-rating">${v}</div>
        <p class="feedback-descr">${l}</p>
        <p class="feedback-name">${r}</p>
      </div>`}).join(""),n=`
    <div class="swiper modal-product__slider">
      <div class="custom-swiper-button-prev">
        <svg class="swiper-nav-icon" width="24" height="24">
          <use href="${f}#icon-left-arrow-alt"></use>
        </svg>
      </div>
      <div class="swiper-wrapper">
        ${t}
      </div>
      <div class="custom-swiper-button-next">
        <svg class="swiper-nav-icon" width="24" height="24">
          <use href="${f}#icon-right-arrow-alt"></use>
        </svg>
      </div>
      <div class="swiper-pagination custom-pagination"></div>
    </div>
    <div class="btn-container">
        <button class="feedback-btn" id="leaveFeedbackBtn">Leave feedback</button>
    </div>
  `,o=document.querySelector(".feedback-container");o.innerHTML=n,new U(".modal-product__slider",{speed:1e3,slidesPerView:1,spaceBetween:10,navigation:{nextEl:".custom-swiper-button-next",prevEl:".custom-swiper-button-prev"},pagination:{el:".swiper-pagination",clickable:!0,renderBullet:function(s,r){return s<3?`<span class="${r}" data-bullet="${s}"></span>`:""}},on:{slideChange:function(s){const r=document.querySelectorAll(".swiper-pagination span");r.forEach(M=>M.classList.remove("swiper-pagination-bullet-active"));const i=s.activeIndex,l=s.slides.length;i===0?r[0].classList.add("swiper-pagination-bullet-active"):i===l-1?r[2].classList.add("swiper-pagination-bullet-active"):r[1].classList.add("swiper-pagination-bullet-active");const p=document.querySelector(".custom-swiper-button-prev"),v=document.querySelector(".custom-swiper-button-next");p.classList.toggle("disabled",i===0),v.classList.toggle("disabled",i===l-1)}},autoplay:{delay:5e3}})}async function K(){try{const e=await D();if(e&&e.data){const n=[...e.data].sort(()=>Math.random()-.5).slice(0,3);J(n)}else console.warn("No feedbacks found or wrong format:",e)}catch(e){console.error("Failed to load feedbacks:",e)}}K();const W=document.querySelectorAll("section[id]"),Q=document.querySelectorAll(".nav-menu-link"),X=document.querySelector(".header"),P=X.offsetHeight,R=100;window.addEventListener("scroll",()=>{let e=null;W.forEach(t=>{const n=t.getBoundingClientRect(),o=t.getAttribute("id");n.top<=P+R&&n.bottom>P+R&&(e=o)}),Q.forEach(t=>{t.getAttribute("href").replace("#","")===e?t.classList.add("active"):t.classList.remove("active")})});(()=>{const e=document.querySelector(".js-menu-container"),t=document.querySelector(".js-open-menu"),n=document.querySelector(".js-close-menu"),o=()=>{const s=e.querySelectorAll('a[href*="#"]'),r=t.getAttribute("aria-expanded")==="true"||!1;t.setAttribute("aria-expanded",!r),e.classList.toggle("is-open"),r?(x(document.body),s.forEach(i=>{i.removeEventListener("click",o)})):(_(document.body),s.forEach(i=>{i.addEventListener("click",o)}))};t.addEventListener("click",o),n.addEventListener("click",o),window.matchMedia("(min-width: 767px)").addEventListener("change",s=>{s.matches&&(e.classList.remove("is-open"),t.setAttribute("aria-expanded",!1),x(document.body))})})();const F="/project-okak/assets/no-image-aiJRBcV6.jpg",j=document.querySelector(".artists-block-list"),N=document.querySelector(".loader"),S=document.querySelector(".artists-load-more"),O=document.querySelector(".artists-silence-block");function Y(){O.classList.remove("hidden")}function C(){O.classList.add("hidden")}function q(){j.innerHTML=""}function Z(){N.classList.remove("hidden")}function y(){N.classList.add("hidden")}function ee(){S.classList.remove("hidden")}function E(){S.classList.add("hidden")}function te(e){const t=e.map(({_id:n,strArtist:o,strBiographyEN:s,strArtistThumb:r,genres:i})=>`<div class="artist-block">
      <img class="artist-img" src="${r||F}" alt="${o}" loading="lazy" onerror="this.onerror=null; this.src='${F}';">
      ${se(i)}
      <h5 class="artist-name">${c(o)}</h5>
      <p class="artist-description">${ne(c(s),200)}</p>
      <a class="artist-learn-link">Learn More
        <svg class="artist-link-icon" width="24" height="24">
          <use href="./icons.svg#arrow-right" data-id="${n}"></use>
        </svg>
      </a>
    </div>`).join("");j.insertAdjacentHTML("beforeend",t)}function se(e=[]){return!Array.isArray(e)||e.length===0?"":`<ul class="artist-genres-list">${e.map(n=>`<li class="artist-genres-item">${c(n)}</li>`).join("")}</ul>`}function c(e=""){return e.replace(/[&<>"']/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"})[t])}function ne(e,t){return e?e.length>t?e.slice(0,t)+"…":e:""}function re(){const e=document.querySelector(".artist-block");if(!e)return;const t=e.getBoundingClientRect().height;window.scrollBy({top:t,behavior:"smooth"})}const oe=document.querySelector(".filter-genre-dropbox");function ie(e){const t=e.map(({genre:n})=>`<input id="genre-${c(n)}" class="filter-genre-input" type="radio" name="genreGroup" value="${c(n)}" />
    <label for="genre-${c(n)}" class="filter-genre-label">${c(n)}</label>`).join("");oe.insertAdjacentHTML("beforeend",t)}const b=document.querySelector(".artists-filter-toggle"),H=document.querySelector(".artists-filter-form"),L=document.querySelector(".filter-sorting-toggle"),ae=document.querySelector(".filter-sorting-dropbox"),w=document.querySelector(".filter-genre-toggle"),ce=document.querySelector(".filter-genre-dropbox");b.addEventListener("click",()=>{H.classList.toggle("open"),b.classList.toggle("open"),b.querySelector(".filter-toggle-icon").classList.toggle("rotate")});L.addEventListener("click",()=>{ae.classList.toggle("open"),L.classList.toggle("open"),L.querySelector(".filter-sorting-icon").classList.toggle("rotate")});w.addEventListener("click",()=>{ce.classList.toggle("open"),w.classList.toggle("open"),w.querySelector(".filter-genre-icon").classList.toggle("rotate")});let B=document.querySelector(".filter-name-input"),$=document.getElementsByName("sortingGroup"),A=document.getElementsByName("genreGroup");function m(e){const t=Array.from(e).find(n=>n.checked);return t?t.value:""}const le=document.querySelector(".artists-filter-reset"),de=document.querySelector(".artists-silence-button");function T(){B.value="",Array.from($).forEach(e=>e.checked=e.id==="filter-default"),Array.from(A).forEach(e=>e.checked=!1),a=1,u=0,q(),C()}le.addEventListener("click",async()=>{T(),await g({page:a})});de.addEventListener("click",async()=>{T(),await g({page:a})});async function g({name:e="",sortName:t="",genre:n="",page:o=1}={}){E(),Z(),C();try{const s=await V({name:e,sortName:t,genre:n,currentPage:o});h=s.totalArtists,h===0?(d.info({message:"Sorry, there are no Artists matching your search query. Please try again!",messageColor:"#fff",position:"topRight",messageSize:"16px",backgroundColor:"#EF4040"}),y(),Y()):(te(s.artists),u+=s.artists.length,y(),ee())}catch(s){d.error({message:"Error loading Artists.",position:"topRight",backgroundColor:"#EF4040"}),console.log("Error: ",s),y()}}let a=1,u=0,h=0;window.addEventListener("DOMContentLoaded",async()=>{a=1,u=0,q(),await g({page:a});const e=await z();e.length>0&&ie(e)});S.addEventListener("click",async()=>{a+=1,await g({name:B.value,sortName:m($),genre:m(A),page:a}),re(),u>=h&&(E(),d.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))});H.addEventListener("change",async e=>{a=1,u=0,q(),await g({name:B.value,sortName:m($),genre:m(A),page:a}),u>=h&&E()});
//# sourceMappingURL=index.js.map
